# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeCalculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='isMeters',
            field=models.BooleanField(default=True),
        ),
    ]
